apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-staging-certificate
  namespace: default
spec:
  secretName: platform-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - __TLS_STAGING_HOST__
